### ISSUE TITLE
compile is deprecated

### ISSUE THREAD

**Issue by kserno** [scana/ok-gradle#6]
with gradle 3.0.0 using compile is deprecated, it has changed to 'implementation'

**Comment by sebokopter** [comment]
The requested proposal is solved in v0.0.2.

But the proposed solution is not optimal. "Ok, Gradle" is such a nice tool that's why I also use it for Java projects. But Gradle Java plugin has no "implementation" configuration instead it is using still "compile". 
Therefore it would be nice if there is possiblity to have different behaviour for android and java plugin/projects.

**Comment by sebokopter** [comment]
Just realized this is marked as won't fix in #2

**Comment by scana** [comment]
Thanks @sebokopter!

This seems like an oversight on my part.
The java-library plugin is already using `implementation` and `api` keywords and I assumed that it's the same for a regular java plugin.

I am working on a new version of ok-gradle, with an ability to automatically add dependencies to your build.gradle files. I will take a look at this, though.

**Comment by scana** [comment]
Closing this issue in favor of the new one.
